config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :relationships, only: [:create, :destroy]
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers, :follow, :follower
    end
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    # ↑resourceが複数形になっていてidを上手く渡せないroute matchエラーが起きていた
  end
  
  root 'home#top'
  get 'home/about', to: 'home#about'
  get 'users/:id/following', to: 'users#following'
  get 'users/:id/followers', to: 'users#followers'
  get '/search' => 'search#search'
  post '/books/:book_id/favorites' => "favorites#create"
  delete '/books/:book_id/favorites' => "favorites#destroy"
end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
	belongs_to :user, optional: true
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!

  def show
		@book = Book.find(params[:id])
		@user = @book.user
		# binding.pry
  end

  def index
		@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
		@book = Book.new
	end

	def create
		@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
		@book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
			@books = Book.all
			# @book = Book.new
			# ↑ create1段目で@bookを定義しており、そこにエラーのデータが入っているのに、再度@book = Book.newを定義し打ち消してしまっていた
			@user = current_user.id
			render :index
  	end
  end

  def edit
		@book = Book.find(params[:id])
		if @book.user == current_user
			render :edit
		else
			redirect_to books_path
		end
  end



  def update
		@book = Book.find(params[:id])
		@user = User.find(current_user.id)
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/views/books/_book.html.erb
<td id="favorite-<%= book.id %>">
  <%= render partial: "like", locals: { book: book } %>
</td>

app/views/books/_favorite.html.erb
<% if Favorite.find_by(user_id: current_user.id, book_id: book.id) %>
  <%= link_to "/books/#{book.id}/favorites", method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end %>
<% else %>
  <%= link_to "/books/#{book.id}/favorites", method: :post, remote: true do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <% end %>
<% end %>
<%= book.favorites.length %>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<!-- エラーメッセージ表示-->
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html copy.erb
<!-- エラーメッセージ表示-->
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

					<%# イイね！ %>
					<td id="favorite-<%= book.id %>">
						<%= render 'favorite', book: book %>
					</td>
					<%# イイね！ %>

					<td>コメント数：<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/index.html.erb
<!-- エラーメッセージ表示-->
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

					<%# イイね！ %>
					<td>
						<% if book.favorited_by?(current_user) %>
							<%= link_to book_favorites_path(book), method: :delete do %>
								<i class="fa fa-heart" aria-hidden="true"></i>	
								<%= book.favorites.count %>
							<% end %>
						<% else %>
							<%= link_to book_favorites_path(book), method: :post do %>
								<i class="fa fa-heart-o" aria-hidden="true"></i>	
								<%= book.favorites.count %>
							<% end %>
						<% end %>
					</td>
					<%# イイね！ %>

					<td>コメント数：<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<!-- エラーメッセージ表示-->
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
							<%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg" %><br>
							<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					
					<% if @book.user.id == current_user.id %>
						<td id="favorite-<%= @book.id %>">
							<%= render 'favorite', book: @book %>
						</td>

						<td>コメント数：<%= @book.book_comments.count %></td>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy", @book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% else %>
						<td id="favorite-<%= @book.id %>">
							<%= render 'favorite', book: @book %>
						</td>
						<td>コメント数：<%= @book.book_comments.count %></td>
					<% end %>
				</tr>
			</table>

		<% if @book.book_comments.any? %>
			<table class="table">
				<% @book.book_comments.each do |comment| %>
					<tr>
						<td><%= comment.body %></td>
						<% if comment.user_id == current_user.id %>
						<%# user_idの時はcurrent_userだけでなく、current_user.idとする %>
							<td class="text-right"><%= link_to 'Destroy', book_book_comment_path(@book, comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger" %></td>
						<% else %>
							<td></td>
						<% end %>
					</tr>
				<% end %>
			</table>
		<% end %>
		<%= form_for ([@book, @book.book_comments.build]) do |f| %>
			<div class="field row">
				<%= f.text_area :body, class: "col-xs-12" %>
			</div>
			<%= f.submit %>
		<% end %>


	</div>
</div>